server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: INFO # 기본 레벨 (root 레벨)
    org.springframework.web: DEBUG # Spring Web 패키지 디버그 레벨

jasypt:
  encryptor:
    bean: jasyptEncryptor
    password: ${ENCRYPT_KEY}

toss:
  clientKey: ENC(E08iHWGLWbHBYjLumRAzEnfJYbMYtSxFosCNW7KQKIa7fOEa07pri039ZBLI7R99)
  secretKey: ENC(5XfXWVOnO2gplto9LnAW0PgKzJ73lmP19sLzszzxbirhZ1JnIjhxKIPXtmeLfh7i)
  securityKey: ENC(hMC3WEM13vDQlnNNqPDnRVT20k8shu+VM3ozN8dC2Xad7QsHIHTI0OSiAh3c58hs3twjULnKoGiWzdc97s2jgMlLWzhpnu/R8F63ZEIodhg=)
